name: flutter_selectable_text
description: A widget that allows to display text like the Text widget, while also allowing actions like selecting and copying text.
version: 0.2.4
author: Danny Valente <valente.danny@gmail.com>
homepage: https://github.com/dannyvalente/flutter_selectable_text

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.7.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  
