name: flutter_selectable_text
description:
  A widget that allows to display text like the Text widget, while also allowing actions like selecting and copying text.

  Because this widget uses the EditableText widget, it does not support RichText nor text spans.

  This will work with different text styles and line heights.
version: 0.2.1
author: Danny Valente <valente.danny@gmail.com>
homepage: https://github.com/dannyvalente/flutter_selectable_text

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.4.7 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  
